### ISSUE TITLE
Error on 2nd load after changing to 1.1.2

### ISSUE THREAD

**Issue by Vystella** [MrFastZombie/ConfigurableVehicles#4]
Hi, i started a savegame with 1.1.1. after updating to 1.1.2.
The warning about the remote driving on tank was printed. So everything was fine.
After saving with 1.1.2 and now reload the savegame. I get this Error.

Error while running event ConfigurableVehicles::on_configuration_changed
__ConfigurableVehicles__/control.lua:2: attempt to index field 'ConfigurableVehicles' (a nil value)
stack traceback:
	__ConfigurableVehicles__/control.lua:2: in function <__ConfigurableVehicles__/control.lua:1>

So any Idea? Thanks 

Edit:
Changes to the settings "Enable tank customization" and "Allow remote driving" (on tank) did not help

**Comment by MrFastZombie** [comment]
so sorry for the crash, that's what I get for trying to do an update late at night.

Looks like this only happens after the game is restarted which is how I missed it in testing. I assumed the value of mod_changes was more save dependent than restart dependent.

Anyways, this was a skill issue on my part. I should've added the nil check to begin with. 

I just uploaded an update that adds a nil check. It may take up to **15 minutes** from when I posted this reply for the in-game mod manager to show the new version. I'm going to close the issue but if the issue persists somehow you can still comment and I'll reopen it if necessary.

**Comment by Vystella** [comment]
Np and Thanks. Works fine!

**Comment by Vystella** [comment]
Hello, here I am again.
Still have the same error on 1.1.3. 
But only when i updated some other Mods.
So I have no idea if it's me, my settings, this mod or other mods.
The only way for me at the moment to solve this issue, is
- Deactivate the Mod
- load the Savegame and overwrite it (or created a new one)  with a new save without the mod
- activate the mod again
- load the new save > works fine.
Updating another mod after that, here comes the error again.
It doesnt matter what for a mod is updated.

**Comment by MrFastZombie** [comment]
Is it giving the exact same error that you initially reported or is there anything different in what it says?

**Comment by Vystella** [comment]
Exact the Same >

Die Mod Configurable Vehicles (1.1.3) hat einen Fehler verursacht, der nicht behoben werden kann.
Bitte informiere den Autor der Mod über diesen Fehler.

Error while running event ConfigurableVehicles::on_configuration_changed
__ConfigurableVehicles__/control.lua:2: attempt to index field 'ConfigurableVehicles' (a nil value)
stack traceback:
	__ConfigurableVehicles__/control.lua:2: in function <__ConfigurableVehicles__/control.lua:1>

**Comment by MrFastZombie** [comment]
I'm gonna take a look at it again.

**Comment by Vystella** [comment]
Thanks, for me is no problem to do my "routine" when its updating another mod. It only takes 20 seconds for me

**Comment by MrFastZombie** [comment]
If you want a temporary solution while I work on this, you can remove control.lua from the zip file. It only contains the code for the warning so it shouldn't break anything in the mod.

**Comment by Vystella** [comment]
Oh yes, I thought that too, but I forgot again.
I have no idea if it makes any difference.
The last 3 changes to the mod folder were:
- updating Shuttle Train Refresh
- updating Asphalt Roads
-  adding Wood Gasification

I had tested it with every single one after doing the Resave without the mod, still happens again.

**Comment by MrFastZombie** [comment]
I think I see the issue now, I'll release an update shortly but first i wanna make sure the conditionals are fool-proof this time.

**Comment by Vystella** [comment]
Thanks for the fast help, take your time with testing it. ^^

**Comment by MrFastZombie** [comment]
I just published a patch, let me know if it works, and sorry about the crashes again!

**Comment by Vystella** [comment]
> I just published a patch, let me know if it works, and sorry about the crashes again!

Working perfect, no errors.
